# -*- coding: utf-8 -*-
"""Imagify.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RP3TRzxi_7ek8hWW3ZqyDW3bUvEMRxfQ
"""

!pip install transformers datasets k_diffusion clip
!pip install transformers # For text processing
!pip install diffusers # For text-to-image diffusion models
!pip install einops # For efficient image manipulation

from transformers import CLIPProcessor, CLIPModel
from diffusers import StableDiffusionPipeline

model_id = "CompVis/stable-diffusion-v1-5"  # Select a suitable model ID
pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")

import datetime
text_prompt = "bag on the bed"

# Generate multiple images for different variations (optional)
for i in range(1):
    image = pipe(text_prompt, guidance_scale=7.5)["images"][0]
    timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    display(image)
    image.save(f"output_image_(timestamp).png")

